name: Bug Report
description: Report incorrect or unexpected behavior.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - adh319
body:
- type: markdown
  attributes:
    value: "Please describe the problem you are having in as much detail as possible:"
- type: textarea
  id: description
  attributes:
    label: "Bug description"
    description: "A clear and concise description of what the bug is."
  validations:
    required: true
- type: textarea
  id: reproduce-step
  attributes:
    label: "Step to reproduce"
    description: "Explain all step to reproduce, with some element that can be particular to your setup and help us to fix it."
    placeholder: "To reproduce, I do ... then ..."
  validations:
    required: true
- type: input
  id: os
  attributes:
    label: Operating system
    description: Which OS does your application run on?
  validations:
    required: true
- type: input
  id: php-version
  attributes:
    label: "Nodejs version"
  validations:
    required: true
    required: true
- type: textarea
  id: error-logs
  attributes:
    label: "Errors / Logs"
    placeholder: "<!-- Paste your logs here -->"
